# Generated by Django 5.0.3 on 2024-09-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_configuracioncorreo_smtp_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='servidorpop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_server', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
